version: "3.7"


services:
  # vBocq-6XQ8qV-JJlU2oNyg
  http-shortner:
    image: plawn/tiny-shortner
    environment:
      REDIS_HOST: redis://redis:6379
      STORE_TYPE: redis
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379