
shortner:
  urlPrefix: "http://localhost:8080"
  store: redis


"%prod%":
  quarkus:
    redis:
      host: ${REDIS_HOST}

"%dev%":
  quarkus:
    redis:
      devservices:
        enabled: true

  shortner:
    urlPrefix: "http://localhost:8080"
    store: in-memory
