

"%prod":
  quarkus:
    redis:
      hosts: ${REDIS_HOST}
  shortner:
    urlPrefix: "http://localhost:8080"
    store: redis

"%dev":
  quarkus:
    redis:
      hosts: ${REDIS_HOST}
      devservices:
        enabled: false

  shortner:
    urlPrefix: "http://localhost:8080"
    store: redis
