

"%prod":
  quarkus:
    redis:
      hosts: ${REDIS_HOST}
  shortner:
    urlPrefix: "http://localhost:8080"
    store: redis

  http:
    cors:
      ~: true
      methods: GET,PUT,POST,DELETE,HEAD,PATCH
      origins: ${CORS_HOST}


"%dev":
  quarkus:
    redis:
      hosts: ${REDIS_HOST}
      devservices:
        enabled: false

  shortner:
    urlPrefix: "http://localhost:8080"
    store: redis
