name: build-docker-jvm

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build_jvm
        uses: docker/build-push-action@v3
        with:
          push: true
          # context: .
          file: ./src/main/docker/Dockerfile.jvm
          # platforms: linux/amd64,linux/arm64
          tags: plawn/tiny-shortner:latest
          
      -
        name: Build and push
        id: docker_build_native
        uses: docker/build-push-action@v3
        with:
          push: true
          # context: .
          file: ./src/main/docker/Dockerfile.native
          # platforms: linux/amd64,linux/arm64
          tags: plawn/tiny-shortner:native
